=== Clement-PhD/CVE-dataset/stats_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "data_folder_path": {
        "type": "string"
      },
      "pull_requests_urls": {
        "type": "array",
        "items": {
          "type": "string",
          "format": "uri"
        }
      },
      "cve_name": {
        "type": "string"
      },
      "repo": {
        "type": "string"
      },
      "warnings": {
        "type": "object",
        "properties": {
          "cve": {
            "type": "string"
          },
          "warnings": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "file_name": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": ["type", "file_name", "message"]
            }
          }
        },
        "required": ["cve", "warnings"]
      },
      "files_extension_stats": {
        "type": "object",
        "additionalProperties": {
          "type": "integer"
        }
      },
      "file_number": {
        "type": "integer"
      },
      "removed_files_number": {
        "type": "integer"
      },
      "added_files_number": {
        "type": "integer"
      },
      "nb_lines_affected": {
        "type": "integer"
      },
      "private_key_files": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "languages": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["data_folder_path", "pull_requests_urls", "cve_name", "repo", "warnings", "files_extension_stats", "file_number", "removed_files_number", "added_files_number", "nb_lines_affected", "private_key_files", "languages"]
  }

=== Clement-PhD/CVE-dataset/data/CVE-2017-6441/stats.json
{
    "data_folder_path": "data/CVE-2017-6441",
    "pull_requests_urls": [
        "https://github.com/php/php-src/pull/2396"
    ],
    "cve_name": "CVE-2017-6441",
    "repo": "php/php-src",
    "warnings": {
        "cve": "CVE-2017-6441",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Zend/tests/declare_006.phpt",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".c": 1,
        ".phpt": 1
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 16,
    "private_key_files": [],
    "languages": [
        "C"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2021-4264/stats.json
{
    "data_folder_path": "data/CVE-2021-4264",
    "pull_requests_urls": [
        "https://github.com/linkedin/dustjs/pull/805"
    ],
    "cve_name": "CVE-2021-4264",
    "repo": "linkedin/dustjs",
    "warnings": {
        "cve": "CVE-2021-4264",
        "warnings": [
            {
                "type": "NO_PATCH",
                "file_name": "dist/dust-full.js",
                "message": "File has no patch data.\n"
            }
        ]
    },
    "files_extension_stats": {
        ".yml": 1,
        ".json": 1,
        ".js": 5
    },
    "file_number": 8,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 194,
    "private_key_files": [],
    "languages": [
        "Javascript"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2023-3724/stats.json
{
    "data_folder_path": "data/CVE-2023-3724",
    "pull_requests_urls": [
        "https://github.com/wolfSSL/wolfssl/pull/6412"
    ],
    "cve_name": "CVE-2023-3724",
    "repo": "wolfSSL/wolfssl",
    "warnings": {
        "cve": "CVE-2023-3724",
        "warnings": []
    },
    "files_extension_stats": {
        ".c": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 13,
    "private_key_files": [],
    "languages": [
        "C"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2021-45385/stats.json
{
    "data_folder_path": "data/CVE-2021-45385",
    "pull_requests_urls": [
        "https://github.com/rockcarry/ffjpeg/pull/48"
    ],
    "cve_name": "CVE-2021-45385",
    "repo": "rockcarry/ffjpeg",
    "warnings": {
        "cve": "CVE-2021-45385",
        "warnings": []
    },
    "files_extension_stats": {
        ".c": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 5,
    "private_key_files": [],
    "languages": [
        "C"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2023-2307/stats.json
{
    "data_folder_path": "data/CVE-2023-2307",
    "pull_requests_urls": [
        "https://github.com/BuilderIO/qwik/pull/3862/commits/09190b70027354baf7ad3d208df9c05a87f75f57"
    ],
    "cve_name": "CVE-2023-2307",
    "repo": "BuilderIO/qwik",
    "warnings": {
        "cve": "CVE-2023-2307",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "packages/qwik-city/middleware/node/http.unit.ts",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".ts": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 49,
    "private_key_files": [],
    "languages": []
}

=== Clement-PhD/CVE-dataset/data/CVE-2023-34460/stats.json
{
    "data_folder_path": "data/CVE-2023-34460",
    "pull_requests_urls": [
        "https://github.com/tauri-apps/tauri/pull/6969#discussion_r1232018347"
    ],
    "cve_name": "CVE-2023-34460",
    "repo": "tauri-apps/tauri",
    "warnings": {
        "cve": "CVE-2023-34460",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": ".changes/config-require-literal_leading_dot.md",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".md": 1,
        ".json": 2,
        ".rs": 2
    },
    "file_number": 5,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 168,
    "private_key_files": [],
    "languages": [
        "Rust"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2021-23807/stats.json
{
    "data_folder_path": "data/CVE-2021-23807",
    "pull_requests_urls": [
        "https://github.com/janl/node-jsonpointer/pull/51"
    ],
    "cve_name": "CVE-2021-23807",
    "repo": "janl/node-jsonpointer",
    "warnings": {
        "cve": "CVE-2021-23807",
        "warnings": []
    },
    "files_extension_stats": {
        ".js": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 34,
    "private_key_files": [],
    "languages": [
        "Javascript"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2021-36157/stats.json
{
    "data_folder_path": "data/CVE-2021-36157",
    "pull_requests_urls": [
        "https://github.com/cortexproject/cortex/pull/4375"
    ],
    "cve_name": "CVE-2021-36157",
    "repo": "cortexproject/cortex",
    "warnings": {
        "cve": "CVE-2021-36157",
        "warnings": []
    },
    "files_extension_stats": {
        ".md": 2,
        ".go": 2
    },
    "file_number": 5,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 80,
    "private_key_files": [],
    "languages": [
        "Go"
    ]
}
