=== Clement-PhD/CVE-dataset/stats_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "data_folder_path": {
        "type": "string"
      },
      "pull_requests_urls": {
        "type": "array",
        "items": {
          "type": "string",
          "format": "uri"
        }
      },
      "cve_name": {
        "type": "string"
      },
      "repo": {
        "type": "string"
      },
      "warnings": {
        "type": "object",
        "properties": {
          "cve": {
            "type": "string"
          },
          "warnings": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "file_name": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": ["type", "file_name", "message"]
            }
          }
        },
        "required": ["cve", "warnings"]
      },
      "files_extension_stats": {
        "type": "object",
        "additionalProperties": {
          "type": "integer"
        }
      },
      "file_number": {
        "type": "integer"
      },
      "removed_files_number": {
        "type": "integer"
      },
      "added_files_number": {
        "type": "integer"
      },
      "nb_lines_affected": {
        "type": "integer"
      },
      "private_key_files": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "languages": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["data_folder_path", "pull_requests_urls", "cve_name", "repo", "warnings", "files_extension_stats", "file_number", "removed_files_number", "added_files_number", "nb_lines_affected", "private_key_files", "languages"]
  }

=== Clement-PhD/CVE-dataset/data/CVE-2022-4741/stats.json
{
    "data_folder_path": "data/CVE-2022-4741",
    "pull_requests_urls": [
        "https://github.com/sajari/docconv/pull/111"
    ],
    "cve_name": "CVE-2022-4741",
    "repo": "sajari/docconv",
    "warnings": {
        "cve": "CVE-2022-4741",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "limit.go",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".go": 5
    },
    "file_number": 5,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 13,
    "private_key_files": [],
    "languages": [
        "Go"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2016-3072/stats.json
{
    "data_folder_path": "data/CVE-2016-3072",
    "pull_requests_urls": [
        "https://github.com/Katello/katello/pull/6051"
    ],
    "cve_name": "CVE-2016-3072",
    "repo": "Katello/katello",
    "warnings": {
        "cve": "CVE-2016-3072",
        "warnings": []
    },
    "files_extension_stats": {
        ".rb": 3
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 30,
    "private_key_files": [],
    "languages": [
        "Ruby"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2019-15536/stats.json
{
    "data_folder_path": "data/CVE-2019-15536",
    "pull_requests_urls": [
        "https://github.com/YourAcclaim/block_acclaim/pull/18"
    ],
    "cve_name": "CVE-2019-15536",
    "repo": "YourAcclaim/block_acclaim",
    "warnings": {
        "cve": "CVE-2019-15536",
        "warnings": []
    },
    "files_extension_stats": {
        ".php": 2,
        ".xml": 1
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 13,
    "private_key_files": [],
    "languages": [
        "PHP"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2023-30261/stats.json
{
    "data_folder_path": "data/CVE-2023-30261",
    "pull_requests_urls": [
        "https://github.com/snaptec/openWB/pull/2673"
    ],
    "cve_name": "CVE-2023-30261",
    "repo": "snaptec/openWB",
    "warnings": {
        "cve": "CVE-2023-30261",
        "warnings": []
    },
    "files_extension_stats": {
        ".php": 3,
        ".sh": 1,
        ".py": 2
    },
    "file_number": 6,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 471,
    "private_key_files": [],
    "languages": [
        "PHP",
        "Python"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2021-41104/stats.json
{
    "data_folder_path": "data/CVE-2021-41104",
    "pull_requests_urls": [
        "https://github.com/esphome/esphome/pull/2409/commits/207cde1667d8c799a197b78ca8a5a14de8d5ca1e"
    ],
    "cve_name": "CVE-2021-41104",
    "repo": "esphome/esphome",
    "warnings": {
        "cve": "CVE-2021-41104",
        "warnings": []
    },
    "files_extension_stats": {
        ".h": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 5,
    "private_key_files": [],
    "languages": [
        "C"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2023-39553/stats.json
{
    "data_folder_path": "data/CVE-2023-39553",
    "pull_requests_urls": [
        "https://github.com/apache/airflow/pull/33074"
    ],
    "cve_name": "CVE-2023-39553",
    "repo": "apache/airflow",
    "warnings": {
        "cve": "CVE-2023-39553",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 23,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2020-36629/stats.json
{
    "data_folder_path": "data/CVE-2020-36629",
    "pull_requests_urls": [
        "https://github.com/SimbCo/httpster/pull/36"
    ],
    "cve_name": "CVE-2020-36629",
    "repo": "SimbCo/httpster",
    "warnings": {
        "cve": "CVE-2020-36629",
        "warnings": []
    },
    "files_extension_stats": {
        ".coffee": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 23,
    "private_key_files": [],
    "languages": []
}

=== Clement-PhD/CVE-dataset/data/CVE-2022-4942/stats.json
{
    "data_folder_path": "data/CVE-2022-4942",
    "pull_requests_urls": [
        "https://github.com/mportuga/eslint-detailed-reporter/pull/46"
    ],
    "cve_name": "CVE-2022-4942",
    "repo": "mportuga/eslint-detailed-reporter",
    "warnings": {
        "cve": "CVE-2022-4942",
        "warnings": []
    },
    "files_extension_stats": {
        ".js": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 15,
    "private_key_files": [],
    "languages": [
        "Javascript"
    ]
}
