=== Clement-PhD/CVE-dataset/stats_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "data_folder_path": {
        "type": "string"
      },
      "pull_requests_urls": {
        "type": "array",
        "items": {
          "type": "string",
          "format": "uri"
        }
      },
      "cve_name": {
        "type": "string"
      },
      "repo": {
        "type": "string"
      },
      "warnings": {
        "type": "object",
        "properties": {
          "cve": {
            "type": "string"
          },
          "warnings": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "file_name": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": ["type", "file_name", "message"]
            }
          }
        },
        "required": ["cve", "warnings"]
      },
      "files_extension_stats": {
        "type": "object",
        "additionalProperties": {
          "type": "integer"
        }
      },
      "file_number": {
        "type": "integer"
      },
      "removed_files_number": {
        "type": "integer"
      },
      "added_files_number": {
        "type": "integer"
      },
      "nb_lines_affected": {
        "type": "integer"
      },
      "private_key_files": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "languages": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["data_folder_path", "pull_requests_urls", "cve_name", "repo", "warnings", "files_extension_stats", "file_number", "removed_files_number", "added_files_number", "nb_lines_affected", "private_key_files", "languages"]
  }

=== Clement-PhD/CVE-dataset/data/CVE-2022-48364/stats.json
{
    "data_folder_path": "data/CVE-2022-48364",
    "pull_requests_urls": [
        "https://github.com/mastodon/mastodon/pull/18525"
    ],
    "cve_name": "CVE-2022-48364",
    "repo": "mastodon/mastodon",
    "warnings": {
        "cve": "CVE-2022-48364",
        "warnings": []
    },
    "files_extension_stats": {
        ".rb": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 3,
    "private_key_files": [],
    "languages": [
        "Ruby"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2016-1902/stats.json
{
    "data_folder_path": "data/CVE-2016-1902",
    "pull_requests_urls": [
        "https://github.com/symfony/symfony/pull/17359"
    ],
    "cve_name": "CVE-2016-1902",
    "repo": "symfony/symfony",
    "warnings": {
        "cve": "CVE-2016-1902",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "src/Symfony/Component/Security/Tests/Core/Util/SecureRandomTest.php",
                "message": "not a modified file (status: FileStatus.REMOVED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".json": 2,
        ".php": 2
    },
    "file_number": 4,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 297,
    "private_key_files": [],
    "languages": [
        "PHP"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2023-25160/stats.json
{
    "data_folder_path": "data/CVE-2023-25160",
    "pull_requests_urls": [
        "https://github.com/nextcloud/mail/pull/7740"
    ],
    "cve_name": "CVE-2023-25160",
    "repo": "nextcloud/mail",
    "warnings": {
        "cve": "CVE-2023-25160",
        "warnings": []
    },
    "files_extension_stats": {
        ".php": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 36,
    "private_key_files": [],
    "languages": [
        "PHP"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2023-5676/stats.json
{
    "data_folder_path": "data/CVE-2023-5676",
    "pull_requests_urls": [
        "https://github.com/eclipse-openj9/openj9/pull/18085"
    ],
    "cve_name": "CVE-2023-5676",
    "repo": "eclipse-openj9/openj9",
    "warnings": {
        "cve": "CVE-2023-5676",
        "warnings": []
    },
    "files_extension_stats": {
        ".c": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 17,
    "private_key_files": [],
    "languages": [
        "C"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2021-31274/stats.json
{
    "data_folder_path": "data/CVE-2021-31274",
    "pull_requests_urls": [
        "https://github.com/librenms/librenms/pull/12739"
    ],
    "cve_name": "CVE-2021-31274",
    "repo": "librenms/librenms",
    "warnings": {
        "cve": "CVE-2021-31274",
        "warnings": []
    },
    "files_extension_stats": {
        ".php": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 2,
    "private_key_files": [],
    "languages": [
        "PHP"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2022-24831/stats.json
{
    "data_folder_path": "data/CVE-2022-24831",
    "pull_requests_urls": [
        "https://github.com/OpenClinica/OpenClinica/pull/3490/commits/b152cc63019230c9973965a98e4386ea5322c18f"
    ],
    "cve_name": "CVE-2022-24831",
    "repo": "OpenClinica/OpenClinica",
    "warnings": {
        "cve": "CVE-2022-24831",
        "warnings": []
    },
    "files_extension_stats": {
        ".java": 3
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 30,
    "private_key_files": [],
    "languages": [
        "Java"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2020-12140/stats.json
{
    "data_folder_path": "data/CVE-2020-12140",
    "pull_requests_urls": [
        "https://github.com/contiki-ng/contiki-ng/pull/1662"
    ],
    "cve_name": "CVE-2020-12140",
    "repo": "contiki-ng/contiki-ng",
    "warnings": {
        "cve": "CVE-2020-12140",
        "warnings": []
    },
    "files_extension_stats": {
        ".c": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 16,
    "private_key_files": [],
    "languages": [
        "C"
    ]
}

=== Clement-PhD/CVE-dataset/data/CVE-2019-11404/stats.json
{
    "data_folder_path": "data/CVE-2019-11404",
    "pull_requests_urls": [
        "https://github.com/arrow-kt/ank/pull/36"
    ],
    "cve_name": "CVE-2019-11404",
    "repo": "arrow-kt/ank",
    "warnings": {
        "cve": "CVE-2019-11404",
        "warnings": []
    },
    "files_extension_stats": {
        ".gradle": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 8,
    "private_key_files": [],
    "languages": []
}
